# Generated by Django 2.1.4 on 2018-12-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='country',
        ),
    ]
