# Generated by Django 2.1.4 on 2018-12-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.CharField(choices=[('massage', 'Massage'), ('sex', 'Sex')], max_length=30),
        ),
    ]
