# Generated by Django 2.1.1 on 2018-12-24 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181223_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_choosen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
