# Generated by Django 2.1.1 on 2018-12-24 20:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181224_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_choosen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 24, 20, 47, 2, 487501, tzinfo=utc)),
        ),
    ]
