# Generated by Django 2.1.1 on 2018-12-25 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181225_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_choosen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 25, 7, 13, 13, 191173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.CharField(choices=[('massage', 'Massage'), ('sex', 'Sex'), ('escort', 'Escort')], default='sex', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(choices=[('1', '1 hour'), ('2', '2 hours'), ('night', 'Full Night'), ('day', '1 Day')], default='2', max_length=30),
        ),
    ]
